- name: Install Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present


- name: Install nginx
  hosts: webservers
  become: yes
  tasks:
    - name: install Nginx 
      apt:
        name: nginx
        state: present