# Using ansible for creating the users populated from a csv file 

# Sample csv file 
username,password,group
alice,Password123!,devteam
bob,SecurePass456,devteam
charlie,MyPa$$789,qa


---
- name: Create users from CSV
  hosts: all
  become: true
  vars:
    user_csv_file: users.csv

  tasks:

    - name: Read user data from CSV
      community.general.read_csv:
        path: "{{ user_csv_file }}"
      register: user_data

    - name: Ensure required groups exist
      group:
        name: "{{ item.group }}"
        state: present
      loop: "{{ user_data.list | unique(attribute='group') }}"

    - name: Create users with group and password
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        group: "{{ item.group }}"
        shell: /bin/bash
        create_home: yes
        state: present
      loop: "{{ user_data.list }}"

    - name: Set proper home directory permissions
      file:
        path: "/home/{{ item.username }}"
        mode: '0750'
        owner: "{{ item.username }}"
        group: "{{ item.group }}"
        state: directory
      loop: "{{ user_data.list }}"

# Creating the users manually not reading from a file. 

---
- name: Create users and set permissions
  hosts: all
  become: true
  vars:
    users:
      - username: alice
        password: "{{ 'Password123!' | password_hash('sha512') }}"
      - username: bob
        password: "{{ 'Password123!' | password_hash('sha512') }}"
      - username: charlie
        password: "{{ 'Password123!' | password_hash('sha512') }}"
    user_group: devteam

  tasks:
    - name: Ensure group "{{ user_group }}" exists
      group:
        name: "{{ user_group }}"
        state: present

    - name: Create users and set password and home
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        group: "{{ user_group }}"
        shell: /bin/bash
        state: present
        create_home: yes
      loop: "{{ users }}"

    - name: Set home directory permissions
      file:
        path: "/home/{{ item.username }}"
        mode: '0750'
        owner: "{{ item.username }}"
        group: "{{ user_group }}"
        state: directory
      loop: "{{ users }}"


ansible-playbook -i hosts.ini create_users.yml

Inventory File hosts.ini

[servers]
server1 ansible_host=192.168.1.100 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
