---
# This creates one ConfigMap named app-config with 3 key-value pairs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENV: "production"
  LOG_LEVEL: "info"
  TIMEOUT: "30"


---
# This creates two separate ConfigMaps: app-config and db-config.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "localhost"
  DB_PORT: "5432"
