---
- name: Join Windows machine to AD domain
  hosts: win_clients
  tasks:
    - win_domain_membership:
        dns_domain_name: pumej.com
        domain_username: "Administrator@pumej.com"
        domain_password: "Emekulus@1234"
        state: domain
      register: domain_state

    - win_reboot:
      when: domain_state.reboot_required
