---
- name: Join Windows machine to AD domain
  hosts: win_clients
  tasks:
    - name: Join the Windows machine to the domain
      microsoft.ad.membership:
        dns_domain_name: pumej.com
        domain_admin_user: "Administrator@pumej.com"
        domain_admin_password: "Emekulus@1234"
        state: domain
      register: domain_state

    - name: Reboot if required
      win_reboot:
        reboot_timeout: 1200
      when: domain_state.reboot_required | default(false)
      register: reboot_result

